### ISSUE TITLE
Problems building LV2 on Linux

### ISSUE THREAD

**Issue by tank-trax** [osxmidi/ScorchCrafter#2]
First thanks for compiling this plug in for Linux. 

I would like to bring a few things to your attention. For some reason the VST chews up a considerable amount of resources, upwards of 50% when using it in Reaper. 

I tried to build it from scratch but only the LADSPA is recognized, however there is no GUI. The VST builds but is not recognized by any program that I have tried scanning the folder it resides in.

The LV2 was missing the manifest and TTL files. After compilation I ran make in the top level folder and it populated those files but won't load in any DAW's that allow for LV2 plugs.

I am using Debian Stretch. I followed the instructions to the letter but no success.

**Comment by tank-trax** [comment]
I tried the Linux VST (released on 18 Nov 2017 ) in Tracktion7 and it ran smoothly. Very low CPU usage. I will see if there's a way to get to lighten up in Reaper. Obviously a Reaper issue.

The LADSPA although without a GUI sounds great in Tracktion/Waveform. Would still like to build the LV2. Any help would be appreciated.

**Comment by tank-trax** [comment]
I would like to confirm that the VST (with GUI) and the LADSPA (no GUI) build successfully.

The LV2 however only builds the Scorch.lv2 folder with one file in it name Scorch_dsp.so

I noticed a new Makefile in the ScorchcrafterGUI folder 
Running make will ->
Generate ttl data for './Scorch_dsp.so', basename: 'Scorch_dsp'
Writing manifest.ttl... done!
Writing Scorch_dsp.ttl... done!
Writing Scorch_ui.ttl... done!
Writing presets.ttl... done!

However the LV2 is not recognized
lv2ls will return
error: /home/username/.lv2/Scorch.lv2/manifest.ttl:6:2: invalid IRI character ` ' (escape %20)
error: /home/username/.lv2/Scorch.lv2/manifest.ttl:6:2: bad subject

The referenced part of the code is the empty bracket in the following of manifest.ttl

```
< >
    a lv2:Plugin ;
    lv2:binary <Scorch_dsp.so> ;
    rdfs:seeAlso <Scorch_dsp.ttl> .
```

something similar in Scorch_dsp.ttl

```
< >
    a lv2:Plugin ;

    lv2:extensionData <http://lv2plug.in/ns/ext/state#interface> ,
                      <http://kxstudio.sf.net/ns/lv2ext/programs#Interface> ;

    lv2:optionalFeature <http://lv2plug.in/ns/lv2core#hardRTCapable> ,
                        <http://lv2plug.in/ns/ext/buf-size#boundedBlockLength> ;

    lv2:requiredFeature <http://lv2plug.in/ns/ext/options#options> ,
                        <http://lv2plug.in/ns/ext/urid#map> ;
```

**Comment by tank-trax** [comment]
@osxmidi 

to add... manifest.ttl references a file that does not exist

```
< #UI>
    a ui:X11UI ;
    ui:binary <Scorch_ui.so> ;
    rdfs:seeAlso <Scorch_ui.ttl> .

```
There does not appear to be any file named Scorch_ui.so anywhere to be found.

**Comment by osxmidi** [comment]
Scorchcrafter needs a quad core cpu because that was how it was written.

I havn't tried building a LV2, Scorchcrafter uses a modified dpf in the project files.

**Comment by tank-trax** [comment]
I have a quad core. The LADSPA and VST build and run perfectly. Would be nice to have the LV2 version.

**Comment by tank-trax** [comment]
Recently and successfully built the LV2. Thank you :-)

A few things of note.

The URL

```
lv2ls | grep Scorch
urn:scorchcrafter:Scorch
```
I use a sample rate of 48 kHz in JACK and when running Scorch using 

`jalv -s urn:scorchcrafter:Scorch`

get this message

```
Parent Window Id missing, host should be using ui:showInterface...
WARNING: this host does not send sample-rate information for LV2 UIs, using 44100 as fallback (this could be wrong)
```

**Comment by osxmidi** [comment]
> Recently and successfully built the LV2. Thank you :-)
> 
> A few things of note.
> 
> The URL
> 
> ```
> lv2ls | grep Scorch
> urn:scorchcrafter:Scorch
> ```
> 
> I use a sample rate of 48 kHz in JACK and when running Scorch using
> 
> `jalv -s urn:scorchcrafter:Scorch`
> 
> get this message
> 
> ```
> Parent Window Id missing, host should be using ui:showInterface...
> WARNING: this host does not send sample-rate information for LV2 UIs, using 44100 as fallback (this could be wrong)
> ```

Turns out that 

WARNING: this host does not send sample-rate information for LV2 UIs, using 44100 as fallback (this could be wrong)

is due to a known bug in plugins built with an old version of DPF.

I'll try to update DPF.

**Comment by osxmidi** [comment]
> Recently and successfully built the LV2. Thank you :-)
> 
> A few things of note.
> 
> The URL
> 
> ```
> lv2ls | grep Scorch
> urn:scorchcrafter:Scorch
> ```
> 
> I use a sample rate of 48 kHz in JACK and when running Scorch using
> 
> `jalv -s urn:scorchcrafter:Scorch`
> 
> get this message
> 
> ```
> Parent Window Id missing, host should be using ui:showInterface...
> WARNING: this host does not send sample-rate information for LV2 UIs, using 44100 as fallback (this could be wrong)
> ```

I've updated DPF.

**Comment by tank-trax** [comment]
It may be innocuous. I use 48 kHz and there are no xruns or popping. I tried the new DPF and same thing.

```
jalv.gtk3 urn:scorchcrafter:Scorch
Plugin:       urn:scorchcrafter:Scorch
UI:           urn:scorchcrafter:Scorch#UI
JACK Name:    Scorch
Sample rate:  48000 Hz
Block length: 512 frames
MIDI buffers: 32768 bytes
Comm buffers: 524288 bytes
Update rate:  25.0 Hz

JACK Name:    Scorch
smp_on          = 0.020000
smp_off         = 0.020000
master_v        = 0.500000
in_boost        = 0.000000
gain            = 0.500000
bright          = 0.000000
channel         = 0.500000
q_bass          = 0.500000
q_mid           = 0.500000
q_treble        = 0.500000
q_pres          = 0.500000
q_contr         = 0.500000
ns_filt         = 0.000000
filt_lev        = 0.600000
WARNING: this host does not send sample-rate information for LV2 UIs, using 44100 as fallback (this could be wrong)
``

**Comment by osxmidi** [comment]
> It may be innocuous. I use 48 kHz and there are no xruns or popping. I tried the new DPF and same thing.
> 
> ```
> jalv.gtk3 urn:scorchcrafter:Scorch
> Plugin:       urn:scorchcrafter:Scorch
> UI:           urn:scorchcrafter:Scorch#UI
> JACK Name:    Scorch
> Sample rate:  48000 Hz
> Block length: 512 frames
> MIDI buffers: 32768 bytes
> Comm buffers: 524288 bytes
> Update rate:  25.0 Hz
> 
> JACK Name:    Scorch
> smp_on          = 0.020000
> smp_off         = 0.020000
> master_v        = 0.500000
> in_boost        = 0.000000
> gain            = 0.500000
> bright          = 0.000000
> channel         = 0.500000
> q_bass          = 0.500000
> q_mid           = 0.500000
> q_treble        = 0.500000
> q_pres          = 0.500000
> q_contr         = 0.500000
> ns_filt         = 0.000000
> filt_lev        = 0.600000
> WARNING: this host does not send sample-rate information for LV2 UIs, using 44100 as fallback (this could be wrong)
> ``
> ```

The Scorch.lv2 has a dsp and a ui file.

If I just load the dsp file (no ui) using jalv then it's ok.

So I think it might be something to do with how jalv handles lv2's with distrho's (dpf) separate dsp and ui files.

The Scorch.lv2 seems to be ok with Ardour.

**Comment by tank-trax** [comment]
I think this issue can be closed now. Thanks!
