### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [osxmidi/ScorchCrafter#5]
Hi there, 1st of all thanks for your awesome (voluntary) work !

Since we've doxed this git in our [HyMPS project](https://github.com/forart/HyMPS) (under [Effects](https://github.com/forart/HyMPS/blob/main/AudioFXs.md#audio---effects-) - [Guitar](https://github.com/forart/HyMPS/blob/main/Guitar.md#audio---effects---guitar-) - [Amp Sims](https://github.com/forart/HyMPS/blob/main/Guitar.md#amp-sims-) section), can you please fix licensing terms for it ?

Our "problem" is that the relative license badge isn't generated correctly:

![](https://flat.badgen.net/github/license/osxmidi/ScorchCrafter)
(generator URL: https://flat.badgen.net/github/license/osxmidi/ScorchCrafter)

This could be easily fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, this may help other devs to understand how reuse your code in other open projects and vice-versa that's a determining factor for the success and longevity of your project.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by osxmidi** [comment]
> Hi there, 1st of all thanks for your awesome (voluntary) work !
> 
> Since we've doxed this git in our [HyMPS project](https://github.com/forart/HyMPS) (under [Effects](https://github.com/forart/HyMPS/blob/main/AudioFXs.md#audio---effects-) - [Guitar](https://github.com/forart/HyMPS/blob/main/Guitar.md#audio---effects---guitar-) - [Amp Sims](https://github.com/forart/HyMPS/blob/main/Guitar.md#amp-sims-) section), can you please fix licensing terms for it ?
> 
> Our "problem" is that the relative license badge isn't generated correctly:
> 
> ![](https://camo.githubusercontent.com/6902185aa127ff059b6447a238d4e59fd17b3df33388fe3afa06c82f37f94ab2/68747470733a2f2f666c61742e62616467656e2e6e65742f6769746875622f6c6963656e73652f6f73786d6964692f53636f72636843726166746572) (generator URL: https://flat.badgen.net/github/license/osxmidi/ScorchCrafter)
> 
> This could be easily fixed by choosing a "correct" license file through the GH's wizard.
> 
> Although it may sounds like a minor aspect, this may help other devs to understand how reuse your code in other open projects and vice-versa that's a determining factor for the success and longevity of your project.
> 
> Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.
> 
> Thanks in advance.

Hi,

I've added a GPL3 license.

**Comment by MarcoRavich** [comment]
Thanks for the timely fix!

As you can see (above too) the badge is now generated rightly.

Your "correct" license setting for this git (which should solve the old @destructavator's - still open - [issue](https://github.com/osxmidi/ScorchCrafter/issues/1) too), caused its placement change in the list:

https://github.com/forart/HyMPS/blob/main/Guitar.md#amp-sims-

The reason is that we have recently introduced a (hopefully) dev-oriented sorting: we've decided to group+sort projects by multiple criterias - the "sorting chain" we adopted actually is: Section > Subsection > Language > License > Alphabetical - and will therefore showed in a slightly different way. 

Do you think this new approach could better foster collaboration between devs? Do you have any suggestions on this?

Thanks again and, if you like/need, let us know (by participating in [our discussions](https://github.com/forart/HyMPS/discussions) too) how can we better support listed projects.

Last but not least, Happy New Year !

**Comment by osxmidi** [comment]
> Thanks for the timely fix!
> 
> As you can see (above too) the badge is now generated rightly.
> 
> Your "correct" license setting for this git (which should solve the old @destructavator's - still open - [issue](https://github.com/osxmidi/ScorchCrafter/issues/1) too), caused its placement change in the list:
> 
> https://github.com/forart/HyMPS/blob/main/Guitar.md#amp-sims-
> 
> The reason is that we have recently introduced a (hopefully) dev-oriented sorting: we've decided to group+sort projects by multiple criterias - the "sorting chain" we adopted actually is: Section > Subsection > Language > License > Alphabetical - and will therefore showed in a slightly different way.
> 
> Do you think this new approach could better foster collaboration between devs? Do you have any suggestions on this?
> 
> Thanks again and, if you like/need, let us know (by participating in [our discussions](https://github.com/forart/HyMPS/discussions) too) how can we better support listed projects.
> 
> Last but not least, Happy New Year !

All ok, Thanks.
